# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1
      - image: circleci/mysql:5.7

    steps:
      - checkout

      - run:
          name: Install MySQL
          command: |
            sudo apt-get install mysql-client
            sudo docker-php-ext-install pdo_mysql
            sudo mysql -h 127.0.0.1 -u root -e "create database circleci_test"

      - run:
          name: Configure environment
          command: cp .env.circleci .env

      - run:
          name: Run Composer
          command: composer install --prefer-dist --no-interaction

      - run:
          name: Migrate database
          command: ./artisan migrate

      - run:
          name: Run PHPUnit
          command: ./vendor/bin/phpunit